Traceback (most recent call last):
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mfvargas/miniconda3/envs/pf3311/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = float("8,5")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_46348/2988467274.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mx[0m [0;34m=[0m [0mfloat[0m[0;34m([0m[0;34m"8,5"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mValueError[0m: could not convert string to float: '8,5'
ValueError: could not convert string to float: '8,5'

